# Generated by Django 5.1 on 2026-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPD_pharm2', '0003_opd2administereddrugs_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opd2administereddrugs',
            name='total',
        ),
        migrations.AddField(
            model_name='opd2administereddrugs',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
