from django.core.management.base import BaseCommand
from queue_operations.models import PresentingComplaint

class Command(BaseCommand):
    help = 'Load complaints seed data'

    def handle(self, *args, **options):
        complaints_data = [
            # General/Constitutional
                    ('general', 'Fatigue / Tiredness'),
                    ('general', 'Fever / Chills / Sweats'),
                    ('general', 'Unexplained Weight Loss'),
                    ('general', 'Unexplained Weight Gain'),
                    ('general', 'Malaise / Feeling Unwell'),
                    ('general', 'Night Sweats'),
                    ('general', 'Generalized Body Aches'),
                    ('general', 'Feeling Feverish'),
                    ('general', 'Swollen Glands / Lymph Nodes'),
                    ('general', 'Not Feeling Right'),
                    ('general', 'Chills without Fever'),
                    ('general', 'Appetite Changes'),
                    ('general', 'Recent Travel History'),
                    ('general', 'Exposure to Sick Contacts'),
                    ('general', 'Insomnia / Sleep Disturbance'),
                    ('general', 'Chronic Pain - Unspecified'),
                    ('general', 'Post-COVID Symptoms / Long COVID'),
                    ('general', 'Exposure to Communicable Disease'),
                    
                    # Neurological
                    ('neurological', 'Headache'),
                    ('neurological', 'Dizziness / Lightheadedness'),
                    ('neurological', 'Vertigo (Room Spinning)'),
                    ('neurological', 'Fainting / Loss of Consciousness (Syncope)'),
                    ('neurological', 'Seizure / Convulsion'),
                    ('neurological', 'Numbness / Tingling (Paresthesia)'),
                    ('neurological', 'Weakness (Generalized or Localized)'),
                    ('neurological', 'Tremors / Shaking'),
                    ('neurological', 'Memory Loss / Confusion'),
                    ('neurological', 'Vision Changes / Blurred Vision / Double Vision'),
                    ('neurological', 'Difficulty Speaking (Slurred Speech)'),
                    ('neurological', 'Loss of Balance / Coordination Problems'),
                    ('neurological', 'Migraine'),
                    ('neurological', 'Facial Droop / Asymmetry'),
                    ('neurological', 'Gait Disturbance'),
                    ('neurological', 'Blackouts / Near Syncope'),
                    ('neurological', 'Speech Difficulty (Aphasia)'),
                    ('neurological', 'Sudden Severe Headache / Thunderclap Headache'),
                    ('neurological', 'Neuropathic Pain / Burning Sensation'),
                    ('neurological', 'Involuntary Movements'),
                    ('neurological', 'Restless Legs'),
                    ('neurological', 'Burning Feet / Hands'),
                    ('neurological', 'Hand Tremor'),
                    
                    # Cardiovascular & Respiratory
                    ('cardiovascular', 'Chest Pain / Chest Tightness'),
                    ('cardiovascular', 'Shortness of Breath / Dyspnea'),
                    ('cardiovascular', 'Palpitations / Irregular Heartbeat'),
                    ('cardiovascular', 'Cough (Dry or Productive)'),
                    ('cardiovascular', 'Coughing up Blood (Hemoptysis)'),
                    ('cardiovascular', 'Wheezing'),
                    ('cardiovascular', 'Swelling in Legs / Ankles (Edema)'),
                    ('cardiovascular', 'Leg Pain with Walking (Claudication)'),
                    ('cardiovascular', 'High Blood Pressure'),
                    ('cardiovascular', 'Low Blood Pressure'),
                    ('cardiovascular', 'Fainting on Exertion'),
                    ('cardiovascular', 'Orthopnea / PND'),
                    ('cardiovascular', 'Cyanosis / Blue Lips or Fingers'),
                    ('cardiovascular', 'Productive Cough with Sputum'),
                    ('cardiovascular', 'Decreased Exercise Tolerance'),
                    ('cardiovascular', 'Dizziness on Standing (Orthostatic)'),
                    ('cardiovascular', 'Leg Ulcers / Non-healing Wound'),
                    ('cardiovascular', 'Cold Extremities'),
                    ('cardiovascular', 'Syncope with Injury'),
                    ('cardiovascular', 'Varicose Vein Pain'),
                    
                    # Gastrointestinal
                    ('gastrointestinal', 'Abdominal Pain / Stomach Ache'),
                    ('gastrointestinal', 'Nausea / Vomiting'),
                    ('gastrointestinal', 'Vomiting Blood (Hematemesis)'),
                    ('gastrointestinal', 'Diarrhea'),
                    ('gastrointestinal', 'Constipation'),
                    ('gastrointestinal', 'Blood in Stool / Black Tarry Stool (Melena)'),
                    ('gastrointestinal', 'Heartburn / Indigestion (Dyspepsia)'),
                    ('gastrointestinal', 'Bloating / Gas'),
                    ('gastrointestinal', 'Difficulty Swallowing (Dysphagia)'),
                    ('gastrointestinal', 'Painful Swallowing (Odynophagia)'),
                    ('gastrointestinal', 'Loss of Appetite'),
                    ('gastrointestinal', 'Jaundice (Yellow Skin/Eyes)'),
                    ('gastrointestinal', 'Rectal Pain / Bleeding'),
                    ('gastrointestinal', 'Change in Stool Color'),
                    ('gastrointestinal', 'Change in Stool Caliber / Pencil Thin Stools'),
                    ('gastrointestinal', 'Food Intolerance'),
                    ('gastrointestinal', 'Early Satiety'),
                    ('gastrointestinal', 'Hiccups - Persistent'),
                    ('gastrointestinal', 'Abdominal Distension'),
                    ('gastrointestinal', 'Anal Itching (Pruritus Ani)'),
                    ('gastrointestinal', 'Fecal Incontinence'),
                    ('gastrointestinal', 'Difficulty Passing Gas'),
                    ('gastrointestinal', 'Mucus in Stool'),
                    
                    # Musculoskeletal
                    ('musculoskeletal', 'Joint Pain (Arthralgia)'),
                    ('musculoskeletal', 'Back Pain'),
                    ('musculoskeletal', 'Neck Pain'),
                    ('musculoskeletal', 'Shoulder Pain'),
                    ('musculoskeletal', 'Knee Pain'),
                    ('musculoskeletal', 'Hip Pain'),
                    ('musculoskeletal', 'Muscle Aches (Myalgia)'),
                    ('musculoskeletal', 'Swollen Joint'),
                    ('musculoskeletal', 'Limited Range of Motion'),
                    ('musculoskeletal', 'Injury / Trauma (e.g., Fall, Sprain, Strain)'),
                    ('musculoskeletal', 'Fracture / Suspected Broken Bone'),
                    ('musculoskeletal', 'Morning Stiffness'),
                    ('musculoskeletal', 'Joint Swelling / Redness / Warmth'),
                    ('musculoskeletal', 'Foot Pain / Heel Pain'),
                    ('musculoskeletal', 'Hand / Wrist Pain'),
                    ('musculoskeletal', 'Muscle Weakness - Proximal'),
                    ('musculoskeletal', 'Muscle Cramps / Spasms'),
                    ('musculoskeletal', 'Clicking / Popping Joints'),
                    ('musculoskeletal', 'Postural Problems'),
                    
                    # Genitourinary & Gynecological
                    ('genitourinary', 'Painful Urination (Dysuria)'),
                    ('genitourinary', 'Frequent Urination / Urgency'),
                    ('genitourinary', 'Blood in Urine (Hematuria)'),
                    ('genitourinary', 'Urinary Incontinence / Leakage'),
                    ('genitourinary', 'Difficulty Urinating'),
                    ('genitourinary', 'Penile Discharge / Sores'),
                    ('genitourinary', 'Testicular Pain / Swelling'),
                    ('genitourinary', 'Vaginal Bleeding (Abnormal)'),
                    ('genitourinary', 'Vaginal Discharge / Itching'),
                    ('genitourinary', 'Pelvic Pain / Pressure'),
                    ('genitourinary', 'Missed Period / Amenorrhea'),
                    ('genitourinary', 'Painful Periods (Dysmenorrhea)'),
                    ('genitourinary', 'Breast Lump / Pain'),
                    ('genitourinary', 'Nipple Discharge'),
                    ('genitourinary', 'Erectile Dysfunction'),
                    ('genitourinary', 'Concerns about Pregnancy'),
                    ('genitourinary', 'Nocturia'),
                    ('genitourinary', 'Flank Pain / Kidney Pain'),
                    ('genitourinary', 'Scrotal Mass / Lump'),
                    ('genitourinary', 'Heavy Menstrual Bleeding (Menorrhagia)'),
                    ('genitourinary', 'Spotting Between Periods'),
                    ('genitourinary', 'Menopausal Symptoms / Hot Flashes'),
                    ('genitourinary', 'Infertility Concerns'),
                    ('genitourinary', 'Painful Intercourse (Dyspareunia)'),
                    ('genitourinary', 'Genital Itching / Burning'),
                    ('genitourinary', 'STI Screening Request'),
                    ('genitourinary', 'Contraception Counseling'),
                    ('genitourinary', 'Cloudy Urine'),
                    ('genitourinary', 'Foul-smelling Urine'),
                    ('genitourinary', 'Genital Lesion / Wart'),
                    
                    # ENT & Dental
                    ('ent', 'Earache / Ear Pain'),
                    ('ent', 'Hearing Loss'),
                    ('ent', 'Ringing in Ears (Tinnitus)'),
                    ('ent', 'Ear Discharge'),
                    ('ent', 'Runny Nose / Congestion'),
                    ('ent', 'Nosebleed (Epistaxis)'),
                    ('ent', 'Sinus Pain / Pressure'),
                    ('ent', 'Sore Throat'),
                    ('ent', 'Hoarseness / Voice Changes'),
                    ('ent', 'Toothache / Dental Pain'),
                    ('ent', 'Mouth Sores / Ulcers'),
                    ('ent', 'Bleeding Gums'),
                    ('ent', 'Difficulty Chewing'),
                    ('ent', 'Facial Pain / Pressure'),
                    ('ent', 'Loss of Smell (Anosmia)'),
                    ('ent', 'Loss of Taste (Ageusia)'),
                    ('ent', 'Snoring / Sleep Apnea Concerns'),
                    ('ent', 'Dry Mouth (Xerostomia)'),
                    ('ent', 'Jaw Pain / TMJ Issues'),
                    ('ent', 'Swollen Tonsils'),
                    ('ent', 'Lump in Throat Sensation (Globus)'),
                    ('ent', 'Post-nasal Drip'),
                    ('ent', 'Snoring'),
                    ('ent', 'Mouth Breathing'),
                    
                    # Dermatological
                    ('dermatological', 'Rash / Skin Eruption'),
                    ('dermatological', 'Itching (Pruritus)'),
                    ('dermatological', 'Skin Lesion / Growth / Lump'),
                    ('dermatological', 'Mole Change'),
                    ('dermatological', 'Acne'),
                    ('dermatological', 'Hives (Urticaria)'),
                    ('dermatological', 'Hair Loss'),
                    ('dermatological', 'Brittle Nails / Nail Changes'),
                    ('dermatological', 'Skin Discoloration'),
                    ('dermatological', 'Cut / Laceration'),
                    ('dermatological', 'Bruising Easily'),
                    ('dermatological', 'Sunburn'),
                    ('dermatological', 'Skin Pain / Tenderness'),
                    ('dermatological', 'Wound / Non-healing Sore'),
                    ('dermatological', 'Skin Peeling'),
                    ('dermatological', 'Excessive Sweating (Hyperhidrosis)'),
                    ('dermatological', 'Cold Sores / Oral Herpes'),
                    ('dermatological', 'Warts'),
                    ('dermatological', 'Dandruff / Scalp Issues'),
                    ('dermatological', 'Spider Veins / Varicose Veins'),
                    ('dermatological', 'Insect Bite / Sting'),
                    ('dermatological', 'Bed Bugs / Scabies Concern'),
                    ('dermatological', 'Lice'),
                    
                    # Psychiatric / Behavioral Health
                    ('psychiatric', 'Depression / Low Mood'),
                    ('psychiatric', 'Anxiety / Nervousness'),
                    ('psychiatric', 'Panic Attacks'),
                    ('psychiatric', 'Stress'),
                    ('psychiatric', 'Insomnia / Trouble Sleeping'),
                    ('psychiatric', 'Excessive Sleepiness (Hypersomnia)'),
                    ('psychiatric', 'Mood Swings'),
                    ('psychiatric', 'Hallucinations'),
                    ('psychiatric', 'Suicidal Thoughts'),
                    ('psychiatric', 'Self-Harm'),
                    ('psychiatric', 'Memory Problems'),
                    ('psychiatric', 'Difficulty Concentrating'),
                    ('psychiatric', 'Agitation / Irritability'),
                    ('psychiatric', 'Phobias'),
                    ('psychiatric', 'Substance Use Concerns'),
                    ('psychiatric', 'Alcohol Use Concerns'),
                    ('psychiatric', 'Eating Disorder Symptoms'),
                    ('psychiatric', 'Compulsive Behaviors'),
                    ('psychiatric', 'Social Withdrawal'),
                    ('psychiatric', 'Grief / Bereavement'),
                    ('psychiatric', 'Trauma History / PTSD Symptoms'),
                    ('psychiatric', 'Impulsivity / Risky Behavior'),
                    ('psychiatric', 'Paranoia'),
                    ('psychiatric', 'Medication Side Effects - Psych'),
                    ('psychiatric', 'ADHD Symptoms / Concentration Issues'),
                    
                    # Eye & Vision
                    ('eye', 'Eye Pain'),
                    ('eye', 'Red Eye / Pink Eye'),
                    ('eye', 'Blurred Vision'),
                    ('eye', 'Double Vision (Diplopia)'),
                    ('eye', 'Floaters / Flashes of Light'),
                    ('eye', 'Dry Eyes'),
                    ('eye', 'Excessive Tearing'),
                    ('eye', 'Feeling of Something in Eye (Foreign Body Sensation)'),
                    ('eye', 'Vision Loss (Partial or Complete)'),
                    ('eye', 'Light Sensitivity (Photophobia)'),
                    ('eye', 'Eye Discharge'),
                    ('eye', 'Eyelid Swelling / Stye'),
                    ('eye', 'Itchy Eyes'),
                    ('eye', 'Crossed Eyes / Strabismus'),
                    ('eye', 'Halos Around Lights'),
                    ('eye', 'Sudden Vision Loss'),
                    ('eye', 'Eye Trauma / Injury'),
                    
                    # Endocrine / Metabolic
                    ('endocrine', 'Feeling Thirsty All the Time'),
                    ('endocrine', 'Frequent Urination (Polyuria)'),
                    ('endocrine', 'Heat or Cold Intolerance'),
                    ('endocrine', 'Neck Swelling (Goiter)'),
                    ('endocrine', 'Unexplained Sweating'),
                    ('endocrine', 'Hair Changes / Excess Hair Growth'),
                    ('endocrine', 'Skin Tags'),
                    ('endocrine', 'Delayed Wound Healing'),
                    ('endocrine', 'Tingling in Hands/Feet'),
                    ('endocrine', 'Salt Cravings'),
                    ('endocrine', 'Hypoglycemia Symptoms'),
                    ('endocrine', 'Low Blood Sugar Symptoms'),
                    ('endocrine', 'Excessive Thirst (Polydipsia)'),
                    
                    # Pediatric-Specific
                    ('pediatric', 'Fussy / Irritable Infant'),
                    ('pediatric', 'Poor Feeding (Infant)'),
                    ('pediatric', 'Colic'),
                    ('pediatric', 'Developmental Delay (Not Walking, Not Talking)'),
                    ('pediatric', 'Behavioral Problems'),
                    ('pediatric', 'Bedwetting (Enuresis)'),
                    ('pediatric', 'Growth Concerns'),
                    ('pediatric', 'Common Childhood Rashes (e.g., Chickenpox, Hand-Foot-Mouth)'),
                    ('pediatric', 'Failure to Thrive'),
                    ('pediatric', 'Excessive Crying'),
                    ('pediatric', 'Tugging at Ears'),
                    ('pediatric', 'Breathing Issues During Sleep'),
                    ('pediatric', 'School Performance Issues'),
                    ('pediatric', 'Toilet Training Issues'),
                    ('pediatric', 'Temper Tantrums'),
                    ('pediatric', 'Feeding Difficulties'),
                    
                    # Administrative / Non-Acute
                    ('administrative', 'Medication Refill'),
                    ('administrative', 'Form Completion (e.g., Work, School)'),
                    ('administrative', 'Routine Check-up / Physical'),
                    ('administrative', 'Vaccination / Immunization'),
                    ('administrative', 'Test Results Review'),
                    ('administrative', 'Second Opinion'),
                    ('administrative', 'Health Clearance / Pre-employment Physical'),
                    ('administrative', 'Wellness Visit'),
                    ('administrative', 'Pre-operative Clearance'),
                    ('administrative', 'Travel Medicine Consult'),
                    ('administrative', 'Insurance / Disability Forms'),
                    ('administrative', 'Referral Request'),
                    ('administrative', 'Lab Work Only'),
                    ('administrative', 'Blood Pressure Check'),
                    ('administrative', 'Follow-up Visit'),
                    ('administrative', 'New Patient Visit'),
                    
                    # Allergy/Immunology
                    ('allergy', 'Allergic Reaction'),
                    ('allergy', 'Anaphylaxis / Severe Allergy'),
                    ('allergy', 'Seasonal Allergies / Hay Fever'),
                    ('allergy', 'Food Allergy Symptoms'),
                    ('allergy', 'Drug Reaction / Rash'),
                    ('allergy', 'Angioedema / Swelling of Face/Lips'),
                    ('allergy', 'Recurrent Infections'),
                    
                    # Trauma/Injury 
                    ('trauma', 'Motor Vehicle Accident'),
                    ('trauma', 'Fall / Mechanical Fall'),
                    ('trauma', 'Burn'),
                    ('trauma', 'Animal Bite'),
                    ('trauma', 'Human Bite'),
                    ('trauma', 'Puncture Wound'),
                    ('trauma', 'Head Injury'),
                    ('trauma', 'Assault / Domestic Violence Concerns'),
                    ('trauma', 'Sexual Assault / Rape'),
                    ('trauma', 'Suspected Child Abuse'),
                    ('trauma', 'Work-related Injury'), 

                    # Obstetric 
                    ('obstetric', 'Pregnancy Confirmation'),
                    ('obstetric', 'Prenatal Visit'),
                    ('obstetric', 'Decreased Fetal Movement'),
                    ('obstetric', 'Vaginal Bleeding in Pregnancy'),
                    ('obstetric', 'Contractions / Labor Concerns'),
                    ('obstetric', 'Postpartum Check'),
                    ('obstetric', 'Breastfeeding Issues'),
                    ('obstetric', 'Morning Sickness / Hyperemesis'),

                    # Antenatal - First Trimester
                    ('antenatal', 'Pregnancy Confirmation / Positive Home Test'),
                    ('antenatal', 'First Prenatal Visit'),
                    ('antenatal', 'Nausea and Vomiting of Pregnancy'),
                    ('antenatal', 'Severe Vomiting / Unable to Keep Food Down'), # Hyperemesis
                    ('antenatal', 'Vaginal Spotting in Early Pregnancy'),
                    ('antenatal', 'Vaginal Bleeding in Pregnancy'),
                    ('antenatal', 'Abdominal Cramping in Pregnancy'),
                    ('antenatal', 'Pregnancy Dating / Unsure of LMP'),
                    
                    # Antenatal - Second/Third Trimester
                    ('antenatal', 'Routine Prenatal Visit'), 
                    ('antenatal', 'Decreased Fetal Movement'),
                    ('antenatal', 'Increased Fetal Movement'),
                    ('antenatal', 'Contractions / Preterm Labor Concerns'), 
                    ('antenatal', 'Braxton Hicks / Practice Contractions'),
                    ('antenatal', 'Leaking Fluid / Possible Rupture of Membranes'),
                    ('antenatal', 'Vaginal Discharge in Pregnancy'),
                    ('antenatal', 'Itching in Pregnancy / Cholestasis Concerns'),
                    ('antenatal', 'Swelling in Pregnancy'), 
                    ('antenatal', 'Headache in Pregnancy'), 
                    ('antenatal', 'Visual Changes in Pregnancy'),
                    ('antenatal', 'High Blood Pressure in Pregnancy'), 
                    ('antenatal', 'Epigastric Pain in Pregnancy'),
                    ('antenatal', 'Pelvic Pressure / Pain in Pregnancy'), 
                    ('antenatal', 'Back Pain in Pregnancy'),
                    ('antenatal', 'Sciatica in Pregnancy'),
                    ('antenatal', 'Heartburn in Pregnancy'),
                    ('antenatal', 'Constipation in Pregnancy'),
                    ('antenatal', 'Hemorrhoids in Pregnancy'), 
                    ('antenatal', 'Varicose Veins in Pregnancy'),
                    ('antenatal', 'Shortness of Breath in Pregnancy'),
                    ('antenatal', 'Palpitations in Pregnancy'), 
                    ('antenatal', 'Fatigue in Pregnancy'),
                    ('antenatal', 'Anxiety About Labor / Delivery'), 
                    ('antenatal', 'Glucose Screen Follow-up'), 
                    
                    # Labor & Delivery Related
                    ('antenatal', 'Labor Check / Contractions'), 
                    ('antenatal', 'Post-dates / Past Due Date'),
                    ('antenatal', 'Scheduled Induction'),
                    ('antenatal', 'Scheduled C-Section'),
                    
                    # Postpartum - New Category
                    ('postpartum', 'Routine Postpartum Check'),
                    ('postpartum', 'Postpartum Bleeding / Lochia'), 
                    ('postpartum', 'Heavy Postpartum Bleeding'),
                    ('postpartum', 'Postpartum Depression / Mood Concerns'), 
                    ('postpartum', 'Postpartum Anxiety'),
                    ('postpartum', 'Breast Pain / Engorgement'),
                    ('postpartum', 'Nipple Pain / Cracked Nipples'),
                    ('postpartum', 'Difficulty Breastfeeding / Low Milk Supply'),
                    ('postpartum', 'Mastitis / Breast Infection'), 
                    ('postpartum', 'C-Section Incision Concerns'), 
                    ('postpartum', 'Episiotomy / Perineal Pain'),
                    ('postpartum', 'Postpartum Constipation'), 
                    ('postpartum', 'Postpartum Urinary Incontinence'), 
                    ('postpartum', 'Postpartum Hair Loss'),
                    ('postpartum', 'Birth Control Counseling Postpartum'),
                    
                    # High-Risk Pregnancy Issues
                    ('antenatal', 'History of Preterm Birth'), 
                    ('antenatal', 'History of C-Section'),
                    ('antenatal', 'Gestational Diabetes Check'),
                    ('antenatal', 'History of Preeclampsia'),
                    ('antenatal', 'Twins / Multiple Gestation'), 
                    ('antenatal', 'Advanced Maternal Age >35'),
                    ('antenatal', 'Teenage Pregnancy'),
        ]
        created = 0
        for category, name in complaints_data:
            obj, was_created = PresentingComplaint.objects.get_or_create(
                category=category,
                name=name,
                defaults={'is_active': True}
            )
            if was_created:
                created += 1
        
        self.stdout.write(self.style.SUCCESS(f'Loaded {created} new complaints'))
