from django.core.management.base import BaseCommand
from queue_operations.models import PatientDiagnosis

class Command(BaseCommand):
    help = 'Load diagnosis seed data'

    def handle(self, *args, **options):
        diagnoses_data = [
            # General/Infectious
            ('infectious', 'Acute upper respiratory infection, unspecified', 'J06.9'),
            ('infectious', 'Viral infection, unspecified', 'B34.9'),
            ('infectious', 'COVID-19', 'U07.1'),
            ('infectious', 'Influenza due to unidentified influenza virus', 'J11.1'),
            ('infectious', 'Streptococcal pharyngitis', 'J02.0'),
            ('infectious', 'Acute bronchitis, unspecified', 'J20.9'),
            ('infectious', 'Pneumonia, unspecified organism', 'J18.9'),
            ('infectious', 'Urinary tract infection, site not specified', 'N39.0'),
            ('infectious', 'Acute gastroenteritis', 'A09'),
            ('infectious', 'Cellulitis of other parts of limb', 'L03.119'),
            ('infectious', 'Otitis media, unspecified', 'H66.90'),
            ('infectious', 'Sinusitis, unspecified', 'J01.90'),
            ('infectious', 'Malaria, unspecified', 'B54'),
            ('infectious', 'Typhoid fever', 'A01.0'),
            ('infectious', 'Tuberculosis, unspecified', 'A15.9'),
            ('infectious', 'HIV disease', 'B20'),
            ('infectious', 'Herpes zoster without complications', 'B02.9'),
            ('infectious', 'Candidiasis of unspecified site', 'B37.9'),
            ('infectious', 'Tonsillitis, unspecified', 'J03.90'),
            ('infectious', 'Acute bronchiolitis due to RSV', 'J21.0'),
            ('infectious', 'Scarlet fever', 'A38.9'),
            ('infectious', 'Mononucleosis', 'B27.90'),
            ('infectious', 'Chickenpox without complications', 'B01.9'),
            ('infectious', 'Measles without complications', 'B05.9'),
            ('infectious', 'Mumps without complications', 'B26.9'),
            ('infectious', 'Sepsis, unspecified organism', 'A41.9'),
            ('infectious', 'Gonococcal infection, unspecified', 'A54.9'),
            ('infectious', 'Chlamydial infection, unspecified', 'A56.8'),
            ('infectious', 'Syphilis, unspecified', 'A53.9'),
            ('infectious', 'Clostridioides difficile infection', 'A04.72'),
            ('infectious', 'Salmonella infection, unspecified', 'A02.9'),
            ('infectious', 'Acute hepatitis A', 'B15.9'),
            ('infectious', 'Acute hepatitis B without delta-agent', 'B16.9'),
            ('infectious', 'Chronic viral hepatitis C', 'B18.2'),
            
            # Cardiovascular
            ('cardiovascular', 'Essential (primary) hypertension', 'I10'),
            ('cardiovascular', 'Hypertensive heart disease without heart failure', 'I11.9'),
            ('cardiovascular', 'Atherosclerotic heart disease of native coronary artery', 'I25.10'),
            ('cardiovascular', 'Atrial fibrillation, unspecified', 'I48.91'),
            ('cardiovascular', 'Congestive heart failure, unspecified', 'I50.9'),
            ('cardiovascular', 'Angina pectoris, unspecified', 'I20.9'),
            ('cardiovascular', 'ST elevation (STEMI) myocardial infarction', 'I21.3'),
            ('cardiovascular', 'Non-ST elevation (NSTEMI) myocardial infarction', 'I21.4'),
            ('cardiovascular', 'Deep vein thrombosis (DVT) of lower extremity', 'I82.409'),
            ('cardiovascular', 'Pulmonary embolism without acute cor pulmonale', 'I26.99'),
            ('cardiovascular', 'Varicose veins of lower extremities', 'I83.9'),
            ('cardiovascular', 'Peripheral vascular disease, unspecified', 'I73.9'),
            ('cardiovascular', 'Cardiac arrest', 'I46.9'),
            ('cardiovascular', 'Bradycardia, unspecified', 'R00.1'),
            ('cardiovascular', 'Tachycardia, unspecified', 'R00.0'),
            ('cardiovascular', 'Palpitations', 'R00.2'),
            ('cardiovascular', 'Orthostatic hypotension', 'I95.1'),
            ('cardiovascular', 'Essential hypertension with CKD', 'I12.9'),
            ('cardiovascular', 'Old myocardial infarction', 'I25.2'),
            ('cardiovascular', 'Paroxysmal atrial fibrillation', 'I48.0'),
            ('cardiovascular', 'Supraventricular tachycardia', 'I47.1'),
            ('cardiovascular', 'Premature ventricular depolarization', 'I49.3'),
            ('cardiovascular', 'Heart murmur, unspecified', 'R01.1'),
            ('cardiovascular', 'Chest pain on breathing', 'R07.1'),
            ('cardiovascular', 'Elevated blood pressure reading without diagnosis of HTN', 'R03.0'),
            
            # Respiratory
            ('respiratory', 'Asthma, unspecified', 'J45.909'),
            ('respiratory', 'Asthma with acute exacerbation', 'J45.901'),
            ('respiratory', 'COPD with acute exacerbation', 'J44.1'),
            ('respiratory', 'COPD, unspecified', 'J44.9'),
            ('respiratory', 'Allergic rhinitis due to pollen', 'J30.1'),
            ('respiratory', 'Chronic sinusitis, unspecified', 'J32.9'),
            ('respiratory', 'Acute laryngitis', 'J04.0'),
            ('respiratory', 'Acute epiglottitis', 'J05.1'),
            ('respiratory', 'Pleural effusion, unspecified', 'J90'),
            ('respiratory', 'Respiratory failure, unspecified', 'J96.90'),
            ('respiratory', 'Pneumothorax, unspecified', 'J93.9'),
            ('respiratory', 'Acute nasopharyngitis [common cold]', 'J00'),
            ('respiratory', 'Acute pharyngitis, unspecified', 'J02.9'),
            ('respiratory', 'Acute tracheitis', 'J04.1'),
            ('respiratory', 'Acute bronchiolitis, unspecified', 'J21.9'),
            ('respiratory', 'Pneumonia due to Streptococcus pneumoniae', 'J13'),
            ('respiratory', 'Influenza with pneumonia', 'J11.0'),
            ('respiratory', 'Pulmonary edema', 'J81.0'),
            ('respiratory', 'Hemoptysis', 'R04.2'),
            ('respiratory', 'Wheezing', 'R06.2'),
            
            # Gastrointestinal
            ('gastrointestinal', 'Gastro-esophageal reflux disease without esophagitis', 'K21.9'),
            ('gastrointestinal', 'Gastritis, unspecified', 'K29.70'),
            ('gastrointestinal', 'Irritable bowel syndrome without diarrhea', 'K58.9'),
            ('gastrointestinal', 'Irritable bowel syndrome with diarrhea', 'K58.0'),
            ('gastrointestinal', 'Constipation, unspecified', 'K59.00'),
            ('gastrointestinal', 'Diverticulitis of large intestine without perforation', 'K57.32'),
            ('gastrointestinal', 'Cholelithiasis', 'K80.20'),
            ('gastrointestinal', 'Hemorrhoids, unspecified', 'K64.9'),
            ('gastrointestinal', 'Noninfective gastroenteritis and colitis', 'K52.9'),
            ('gastrointestinal', 'Appendicitis, unspecified', 'K37'),
            ('gastrointestinal', 'Inguinal hernia', 'K40.90'),
            ('gastrointestinal', 'Umbilical hernia', 'K42.9'),
            ('gastrointestinal', 'Peptic ulcer, site unspecified', 'K27.9'),
            ('gastrointestinal', 'Hepatitis, unspecified', 'K75.9'),
            ('gastrointestinal', 'Cirrhosis of liver, unspecified', 'K74.60'),
            ('gastrointestinal', 'Pancreatitis, unspecified', 'K85.9'),
            ('gastrointestinal', 'Anal fissure, unspecified', 'K60.0'),
            ('gastrointestinal', 'Dyspepsia', 'K30'),
            ('gastrointestinal', 'Acute appendicitis with generalized peritonitis', 'K35.2'),
            ('gastrointestinal', 'Ulcerative colitis, unspecified', 'K51.90'),
            ('gastrointestinal', 'Crohn disease, unspecified', 'K50.90'),
            ('gastrointestinal', 'Diarrhea, unspecified', 'R19.7'),
            ('gastrointestinal', 'Nausea', 'R11.0'),
            ('gastrointestinal', 'Vomiting, unspecified', 'R11.10'),
            ('gastrointestinal', 'Abdominal distension (gaseous)', 'R14.0'),
            ('gastrointestinal', 'Dysphagia, unspecified', 'R13.10'),
            ('gastrointestinal', 'Melena', 'K92.1'),
            ('gastrointestinal', 'Hematemesis', 'K92.0'),
            
            # Endocrine/Metabolic
            ('endocrine', 'Type 2 diabetes mellitus without complications', 'E11.9'),
            ('endocrine', 'Type 2 diabetes mellitus with hyperglycemia', 'E11.65'),
            ('endocrine', 'Type 2 diabetes mellitus with diabetic neuropathy', 'E11.40'),
            ('endocrine', 'Type 1 diabetes mellitus without complications', 'E10.9'),
            ('endocrine', 'Hypothyroidism, unspecified', 'E03.9'),
            ('endocrine', 'Hyperthyroidism, unspecified', 'E05.90'),
            ('endocrine', 'Hyperlipidemia, unspecified', 'E78.5'),
            ('endocrine', 'Obesity, unspecified', 'E66.9'),
            ('endocrine', 'Vitamin D deficiency, unspecified', 'E55.9'),
            ('endocrine', 'Dehydration', 'E86.0'),
            ('endocrine', 'Hypokalemia', 'E87.6'),
            ('endocrine', 'Hyponatremia', 'E87.1'),
            ('endocrine', 'Metabolic syndrome', 'E88.81'),
            ('endocrine', 'Gout, unspecified', 'M10.9'),
            ('endocrine', 'Osteoporosis', 'M81.0'),
            ('endocrine', 'Type 1 diabetes mellitus with ketoacidosis', 'E10.10'),
            ('endocrine', 'Type 2 diabetes mellitus with foot ulcer', 'E11.621'),
            ('endocrine', 'Type 2 diabetes mellitus with retinopathy', 'E11.319'),
            ('endocrine', 'Hypoglycemia, unspecified', 'E16.2'),
            ('endocrine', 'Hypercalcemia', 'E83.52'),
            ('endocrine', 'Vitamin B12 deficiency', 'E53.8'),
            ('endocrine', 'Folate deficiency anemia', 'D52.9'),
            ('endocrine', 'Morbid obesity', 'E66.01'),
            ('endocrine', 'Overweight', 'E66.3'),
            
            # Musculoskeletal
            ('musculoskeletal', 'Low back pain', 'M54.50'),
            ('musculoskeletal', 'Cervicalgia', 'M54.2'),
            ('musculoskeletal', 'Sciatica, unspecified side', 'M54.30'),
            ('musculoskeletal', 'Osteoarthritis of knee, unspecified', 'M17.9'),
            ('musculoskeletal', 'Osteoarthritis of hip, unspecified', 'M16.9'),
            ('musculoskeletal', 'Gout, unspecified', 'M10.9'),
            ('musculoskeletal', 'Rheumatoid arthritis, unspecified', 'M06.9'),
            ('musculoskeletal', 'Fibromyalgia', 'M79.7'),
            ('musculoskeletal', 'Sprain of ankle, unspecified', 'S93.409A'),
            ('musculoskeletal', 'Fracture of distal radius, unspecified', 'S52.509A'),
            ('musculoskeletal', 'Shoulder pain', 'M25.511'),
            ('musculoskeletal', 'Knee pain', 'M25.561'),
            ('musculoskeletal', 'Neck pain', 'M54.2'),
            ('musculoskeletal', 'Lumbago with sciatica', 'M54.4'),
            ('musculoskeletal', 'Bursitis of hip', 'M70.70'),
            ('musculoskeletal', 'Tendinitis, unspecified', 'M77.9'),
            ('musculoskeletal', 'Muscle spasm', 'M62.838'),
            ('musculoskeletal', 'Rotator cuff syndrome', 'M75.10'),
            ('musculoskeletal', 'Plantar fascial fibromatosis', 'M72.2'),
            ('musculoskeletal', 'Carpal tunnel syndrome', 'G56.00'), # You have this under neuro - duplicate
            ('musculoskeletal', 'Lateral epicondylitis', 'M77.10'),
            ('musculoskeletal', 'Medial epicondylitis', 'M77.00'),
            ('musculoskeletal', 'Sprain of wrist', 'S63.509A'),
            ('musculoskeletal', 'Sprain of cervical spine', 'S13.4XXA'), # You have as whiplash under injury
            ('musculoskeletal', 'Strain of lumbar region', 'S39.012A'),
            ('musculoskeletal', 'Fracture of clavicle', 'S42.009A'),
            ('musculoskeletal', 'Osteopenia', 'M85.80'),
            ('musculoskeletal', 'Myalgia', 'M79.10'),
            
            # Neurological
            ('neurological', 'Migraine without aura, not intractable', 'G43.009'),
            ('neurological', 'Migraine with aura, not intractable', 'G43.109'),
            ('neurological', 'Tension-type headache, unspecified', 'G44.209'),
            ('neurological', 'Epilepsy, unspecified, not intractable', 'G40.909'),
            ('neurological', 'Cerebral infarction, unspecified', 'I63.9'),
            ('neurological', 'Transient cerebral ischemic attack', 'G45.9'),
            ('neurological', 'Essential tremor', 'G25.0'),
            ('neurological', 'Carpal tunnel syndrome, unspecified upper limb', 'G56.00'),
            ('neurological', 'Dizziness and giddiness', 'R42'),
            ('neurological', 'Syncope and collapse', 'R55'),
            ('neurological', 'Peripheral neuropathy, unspecified', 'G62.9'),
            ('neurological', 'Parkinson disease', 'G20'),
            ('neurological', 'Multiple sclerosis', 'G35'),
            ('neurological', 'Bell palsy', 'G51.0'),
            ('neurological', 'Stroke, unspecified', 'I64'),
            ('neurological', 'Seizure, unspecified', 'R56.9'),
            ('neurological', 'Insomnia due to medical condition', 'G47.01'),
            ('neurological', 'Restless legs syndrome', 'G25.81'),
            ('neurological', 'Trigeminal neuralgia', 'G50.0'),
            ('neurological', 'Vertigo, unspecified', 'R42'), # You have as Dizziness and giddiness
            ('neurological', 'Altered mental status, unspecified', 'R41.82'),
            ('neurological', 'Memory loss', 'R41.3'),
            ('neurological', 'Sleep apnea, unspecified', 'G47.33'),
            
            # Genitourinary
            ('genitourinary', 'Acute kidney failure, unspecified', 'N17.9'),
            ('genitourinary', 'Chronic kidney disease, stage 3', 'N18.3'),
            ('genitourinary', 'Calculus of kidney', 'N20.0'),
            ('genitourinary', 'Benign prostatic hyperplasia without LUTS', 'N40.0'),
            ('genitourinary', 'Erectile dysfunction, unspecified', 'N52.9'),
            ('genitourinary', 'Menopausal and female climacteric states', 'N95.1'),
            ('genitourinary', 'Abnormal uterine and vaginal bleeding', 'N93.9'),
            ('genitourinary', 'Dysmenorrhea, unspecified', 'N94.6'),
            ('genitourinary', 'Endometriosis, unspecified', 'N80.9'),
            ('genitourinary', 'Polycystic ovarian syndrome', 'E28.2'),
            ('genitourinary', 'Uterine fibroids', 'D25.9'),
            ('genitourinary', 'Ovarian cyst', 'N83.20'),
            ('genitourinary', 'Testicular pain', 'N50.819'),
            ('genitourinary', 'Epididymitis', 'N45.9'),
            ('genitourinary', 'Orchitis', 'N45.2'),
            ('genitourinary', 'Urinary incontinence, unspecified', 'R32'),
            ('genitourinary', 'Urinary retention', 'R33.9'),
            ('genitourinary', 'Hematuria, unspecified', 'R31.9'),
            ('genitourinary', 'Proteinuria, unspecified', 'R80.9'),
            ('genitourinary', 'Vaginitis, unspecified', 'N76.0'),
            ('genitourinary', 'Cervicitis', 'N72'),
            ('genitourinary', 'Menorrhagia', 'N92.0'),
            ('genitourinary', 'Amenorrhea, unspecified', 'N91.2'),
            ('genitourinary', 'Erectile dysfunction due to diseases classified elsewhere', 'N52.1'),
            ('genitourinary', 'Hydrocele', 'N43.3'),
            
            # Dermatological
            ('dermatological', 'Atopic dermatitis, unspecified', 'L20.9'),
            ('dermatological', 'Contact dermatitis, unspecified', 'L25.9'),
            ('dermatological', 'Psoriasis, unspecified', 'L40.9'),
            ('dermatological', 'Acne vulgaris', 'L70.0'),
            ('dermatological', 'Urticaria, unspecified', 'L50.9'),
            ('dermatological', 'Actinic keratosis', 'L57.0'),
            ('dermatological', 'Seborrheic keratosis', 'L82.1'),
            ('dermatological', 'Tinea corporis', 'B35.4'),
            ('dermatological', 'Tinea pedis', 'B35.3'),
            ('dermatological', 'Impetigo', 'L01.00'),
            ('dermatological', 'Cellulitis, unspecified', 'L03.90'),
            ('dermatological', 'Abscess, unspecified', 'L02.91'),
            ('dermatological', 'Scabies', 'B86'),
            ('dermatological', 'Alopecia areata', 'L63.9'),
            ('dermatological', 'Dermatitis, unspecified', 'L30.9'),
            ('dermatological', 'Pruritus, unspecified', 'L29.9'),
            ('dermatological', 'Rash, unspecified', 'R21'),
            ('dermatological', 'Erythema, unspecified', 'L53.9'),
            ('dermatological', 'Wart, unspecified', 'B07.9'),
            ('dermatological', 'Molluscum contagiosum', 'B08.1'),
            ('dermatological', 'Herpes simplex, unspecified', 'B00.9'),
            ('dermatological', 'Seborrheic dermatitis, unspecified', 'L21.9'),
            ('dermatological', 'Rosacea, unspecified', 'L71.9'),
            
            # Psychiatric/Behavioral
            ('psychiatric', 'Major depressive disorder, single episode, unspecified', 'F32.9'),
            ('psychiatric', 'Major depressive disorder, recurrent, moderate', 'F33.1'),
            ('psychiatric', 'Generalized anxiety disorder', 'F41.1'),
            ('psychiatric', 'Panic disorder', 'F41.0'),
            ('psychiatric', 'Insomnia, unspecified', 'G47.00'),
            ('psychiatric', 'Attention-deficit hyperactivity disorder, combined type', 'F90.2'),
            ('psychiatric', 'Bipolar disorder, unspecified', 'F31.9'),
            ('psychiatric', 'Post-traumatic stress disorder', 'F43.10'),
            ('psychiatric', 'Alcohol use disorder, mild', 'F10.10'),
            ('psychiatric', 'Schizophrenia, unspecified', 'F20.9'),
            ('psychiatric', 'Adjustment disorder', 'F43.20'),
            ('psychiatric', 'Eating disorder, unspecified', 'F50.9'),
            ('psychiatric', 'Obsessive-compulsive disorder', 'F42.9'),
            ('psychiatric', 'Acute stress disorder', 'F43.0'),
            ('psychiatric', 'Suicidal ideations', 'R45.851'),
            ('psychiatric', 'Homicidal ideations', 'R45.850'),
            ('psychiatric', 'Nicotine dependence, cigarettes', 'F17.210'),
            ('psychiatric', 'Opioid use disorder, unspecified', 'F11.90'),
            ('psychiatric', 'Sleep disorder, unspecified', 'G47.9'),
            
            # Obstetric - Common Diagnoses
            ('obstetric', 'Supervision of normal first pregnancy', 'Z34.00'),
            ('obstetric', 'Supervision of normal pregnancy, third trimester', 'Z34.03'),
            ('obstetric', 'Gestational diabetes mellitus in pregnancy', 'O24.419'),
            ('obstetric', 'Gestational hypertension', 'O13.9'),
            ('obstetric', 'Preeclampsia, unspecified', 'O14.90'),
            ('obstetric', 'Hyperemesis gravidarum, mild', 'O21.0'),
            ('obstetric', 'Threatened abortion', 'O20.0'),
            ('obstetric', 'Preterm labor without delivery', 'O60.03'),
            ('obstetric', 'Anemia complicating pregnancy', 'O99.019'),
            ('obstetric', 'UTI in pregnancy', 'O23.40'),
            ('obstetric', 'Ectopic pregnancy', 'O00.90'),
            ('obstetric', 'Placenta previa', 'O44.00'),
            ('obstetric', 'Premature rupture of membranes', 'O42.90'),
            ('obstetric', 'Prolonged pregnancy', 'O48'),
            ('obstetric', 'Obstructed labor', 'O64.0'),
            ('obstetric', 'Supervision of high-risk pregnancy', 'O09.90'),
            ('obstetric', 'Gestational diabetes, diet controlled', 'O24.410'),
            ('obstetric', 'Gestational diabetes, insulin controlled', 'O24.414'),
            ('obstetric', 'Spontaneous abortion, unspecified', 'O03.9'),
            ('obstetric', 'Labor and delivery complicated by fetal distress', 'O68'),
            ('obstetric', 'Postpartum care immediately after delivery', 'Z39.0'),
            ('postpartum', 'Lactation issues', 'O92.70'),
            
            # Postpartum
            ('postpartum', 'Encounter for postpartum care', 'Z39.2'),
            ('postpartum', 'Postpartum depression', 'F53.0'),
            ('postpartum', 'Mastitis associated with lactation', 'O91.23'),
            ('postpartum', 'Disruption of cesarean delivery wound', 'O90.0'),
            ('postpartum', 'Postpartum hemorrhage', 'O72.1'),
            ('postpartum', 'Postpartum thyroiditis', 'O90.5'),
            
            # Preventive/Z-codes - Very Common
            ('preventive', 'Encounter for general adult medical exam without abnormal findings', 'Z00.00'),
            ('preventive', 'Encounter for general adult medical exam with abnormal findings', 'Z00.01'),
            ('preventive', 'Encounter for well child exam', 'Z00.129'),
            ('preventive', 'Encounter for immunization', 'Z23'),
            ('preventive', 'Encounter for screening for malignant neoplasm of colon', 'Z12.11'),
            ('preventive', 'Encounter for screening mammogram for malignant neoplasm of breast', 'Z12.31'),
            ('preventive', 'Long term current use of anticoagulants', 'Z79.01'),
            ('preventive', 'Long term current use of insulin', 'Z79.4'),
            ('preventive', 'BMI 30.0-39.9, adult', 'Z68.3'),
            ('preventive', 'BMI 40 or over, adult', 'Z68.41'),
            ('preventive', 'Tobacco use', 'Z72.0'),
            ('preventive', 'Encounter for contraceptive management', 'Z30.9'),
            ('preventive', 'Pregnancy test', 'Z32.01'),
            ('preventive', 'Donor of blood', 'Z52.0'),
            ('preventive', 'Encounter for gynecological examination (general) (routine)', 'Z01.419'),
            ('preventive', 'Encounter for follow-up examination after completed treatment', 'Z09'),
            ('preventive', 'Personal history of malignant neoplasm, unspecified', 'Z85.9'),
            ('preventive', 'Family history of malignant neoplasm, unspecified', 'Z80.9'),
            ('preventive', 'Encounter for screening for diabetes mellitus', 'Z13.1'),
            ('preventive', 'Encounter for screening for depression', 'Z13.31'),
            ('preventive', 'Encounter for preprocedural examination', 'Z01.818'),
            ('preventive', 'Encounter for issue of repeat prescription', 'Z76.0'),
            ('preventive', 'Encounter for administrative examination', 'Z02.9'),
            ('preventive', 'Personal history of nicotine dependence', 'Z87.891'),
            ('preventive', 'Family history of diabetes mellitus', 'Z83.3'),
            ('preventive', 'Family history of ischemic heart disease', 'Z82.49'),
            ('preventive', 'Encounter for testing for COVID-19', 'Z11.52'),
            ('preventive', 'Contact with and exposure to COVID-19', 'Z20.822'),
            
            # Injuries/Trauma
            ('injury', 'Concussion', 'S06.0X0A'),
            ('injury', 'Open wound of head', 'S01.90XA'),
            ('injury', 'Superficial injury of ankle', 'S90.90XA'),
            ('injury', 'Burn of unspecified degree of hand', 'T23.001A'),
            ('injury', 'Foreign body in eye', 'T15.90XA'),
            ('injury', 'Whiplash injury', 'S13.4XXA'),
            ('injury', 'Poisoning by unspecified drug', 'T50.901A'),
            
            # Ear/Eye
            ('ear_eye', 'Conjunctivitis, unspecified', 'H10.9'),
            ('ear_eye', 'Cataract, unspecified', 'H26.9'),
            ('ear_eye', 'Glaucoma, unspecified', 'H40.9'),
            ('ear_eye', 'Refractive error, unspecified', 'H52.7'),
            ('ear_eye', 'Hearing loss, unspecified', 'H91.90'),
            ('ear_eye', 'Tinnitus', 'H93.1'),
            
            # Anemia/Hematology
            ('hematology', 'Iron deficiency anemia', 'D50.9'),
            ('hematology', 'Vitamin B12 deficiency anemia', 'D51.9'),
            ('hematology', 'Sickle cell anemia', 'D57.1'),
            ('hematology', 'Anemia, unspecified', 'D64.9'),
            ('hematology', 'Thrombocytopenia, unspecified', 'D69.6'),
            
            # Oncology
            ('oncology', 'Malignant neoplasm of breast', 'C50.919'),
            ('oncology', 'Malignant neoplasm of prostate', 'C61'),
            ('oncology', 'Malignant neoplasm of lung', 'C34.90'),
            ('oncology', 'Malignant neoplasm of colon', 'C18.9'),
            ('oncology', 'Malignant neoplasm of cervix uteri', 'C53.9'),
            ('oncology', 'Benign neoplasm of skin', 'D23.9'),

            # Psychiatric
            ('psychiatric', 'Anxiety disorder, unspecified', 'F41.9'),
            ('psychiatric', 'Depressive episode, unspecified', 'F32.A'),
            ('psychiatric', 'Alcohol abuse, uncomplicated', 'F10.10'),
            ('psychiatric', 'Cannabis use, unspecified', 'F12.90'),

            # Chronic Management
            ('endocrine', 'Type 2 diabetes mellitus with chronic kidney disease', 'E11.22'),
            ('cardiovascular', 'Chronic atrial fibrillation', 'I48.20'),
            ('neurological', 'Alzheimer disease, unspecified', 'G30.9'),
            ('neurological', 'Vascular dementia without behavioral disturbance', 'F01.50'),
            ('musculoskeletal', 'Spinal stenosis, lumbar region', 'M48.061'),

            # Symptoms/R-codes
            ('symptoms', 'Chest pain, unspecified', 'R07.9'),
            ('symptoms', 'Abdominal pain, unspecified site', 'R10.9'),
            ('symptoms', 'Fever, unspecified', 'R50.9'),
            ('symptoms', 'Headache, unspecified', 'R51.9'),
            ('symptoms', 'Shortness of breath', 'R06.02'),
            ('symptoms', 'Cough', 'R05.9'),
            ('symptoms', 'Nausea with vomiting, unspecified', 'R11.2'),
            ('symptoms', 'Generalized fatigue', 'R53.83'),
            ('symptoms', 'Edema, unspecified', 'R60.9'),
            ('symptoms', 'Weight loss', 'R63.4'),
            ('symptoms', 'Abnormal weight gain', 'R63.5'),
            ('symptoms', 'Anorexia', 'R63.0'),
            ('symptoms', 'Malaise and fatigue', 'R53.81'),
            ('symptoms', 'Lymphadenopathy', 'R59.9'),
            ('symptoms', 'Epistaxis', 'R04.0'),
            ('symptoms', 'Night sweats', 'R61'),

            # Pediatrics
            ('pediatrics', 'Hand-foot-and-mouth disease', 'B08.4'),
            ('pediatrics', 'Diaper dermatitis (Diaper rash)', 'L22'),
            ('pediatrics', 'Feeding problem of newborn', 'P92.9'),
            ('pediatrics', 'Croup (Acute obstructive laryngitis)', 'J05.0'),
            ('pediatrics', 'Neonatal jaundice, unspecified', 'P59.9'),
            ('pediatrics', 'Failure to thrive in child', 'R62.51'),
            ('pediatrics', 'Delayed milestone in childhood', 'R62.0'),
            ('pediatrics', 'Newborn affected by maternal infectious disease', 'P00.2'),
            ('pediatrics', 'Febrile seizure, simple', 'R56.00'),
            ('pediatrics', 'Acute bronchiolitis', 'J21.9'),
        ]
        
        created = 0
        updated = 0
        
        for category, description, icd10 in diagnoses_data:
            obj, was_created = PatientDiagnosis.objects.get_or_create(
                icd10_code=icd10,  # Use icd10_code as the unique identifier
                defaults={
                    'category': category,
                    'description': description,
                    'is_active': True
                }
            )
            if was_created:
                created += 1
            else:
                # Update existing records if description changed
                if obj.description != description or obj.category != category:
                    obj.description = description
                    obj.category = category
                    obj.save()
                    updated += 1
        
        self.stdout.write(self.style.SUCCESS(f'✅ Loaded {created} new diagnoses'))
        self.stdout.write(self.style.SUCCESS(f'📝 Updated {updated} existing diagnoses'))
        self.stdout.write(self.style.SUCCESS(f'📊 Total diagnoses in database: {PatientDiagnosis.objects.count()}'))

