# Generated by Django 5.1 on 2026-05-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifystaff',
            options={'ordering': ['-pk']},
        ),
    ]
