# Generated by Django 5.1 on 2026-05-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_verifystaff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifystaff',
            options={},
        ),
    ]
