# Generated by Django 6.1.2 on 2026-10-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_verifystaff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
