# Generated by Django 5.1 on 2026-02-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD', '0002_admissionnote_patient_doctornote_patient_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_type', models.CharField(choices=[('regular', 'Regular Prescription'), ('stat', 'Stat Prescription'), ('prn', 'PRN Prescription'), ('glycemic', 'Glycemic Control Standing Order')], default='regular', max_length=20)),
                ('drug_name', models.CharField(max_length=200)),
                ('dose', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV'), ('im', 'IM'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('inhaled', 'Inhaled')], max_length=20)),
                ('frequency', models.CharField(choices=[('od', 'Once Daily (OD)'), ('bd', 'Twice Daily (BD)'), ('tds', 'Three Times Daily (TDS)'), ('qds', 'Four Times Daily (QDS)'), ('prn', 'As Required (PRN)'), ('stat', 'Stat (Immediate)')], max_length=20)),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientprofile')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_drugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'drug_name'],
            },
        ),
        migrations.CreateModel(
            name='DrugAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('administered_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('administered', 'Administered'), ('missed', 'Missed'), ('refused', 'Refused'), ('held', 'Held')], default='pending', max_length=20)),
                ('is_patient_owned', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('bedside_drug', models.CharField(blank=True, max_length=200)),
                ('quantity_administered', models.CharField(blank=True, max_length=50)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('dose_given', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='IPD.drugprescription')),
            ],
            options={
                'ordering': ['scheduled_time'],
                'unique_together': {('prescription', 'scheduled_time')},
            },
        ),
    ]
