# Generated by Django 5.1 on 2026-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD', '0003_drugprescription_drugadministration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
