# Generated by Django 5.1 on 2026-03-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD', '0005_alter_ward_price_admissionfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionfee',
            name='admission_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IPD.admissiontable'),
        ),
    ]
