# Generated by Django 5.1 on 2026-06-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD', '0006_admissionfee_admission_record'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drugadministration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='drugadministration',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='drugadministration',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drugadministration',
            name='source_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drugadministration',
            name='source_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drugadministration',
            name='source_store',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='drugadministration',
            name='prescription',
        ),
    ]
