# Generated by Django 5.1 on 2026-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0002_invoice_completed_invoice_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
