# Generated by Django 5.1 on 2026-03-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0003_invoice_discount'),
        ('patients', '0002_patientappointment_anc_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientcategory'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_option',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
