# Generated by Django 5.1 on 2026-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0005_transactionupdate_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionupdate',
            name='invoice_ids',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionupdate',
            name='receipt_given_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionupdate',
            name='receipt_ids',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
