# Generated by Django 5.1 on 2026-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0006_transactionupdate_invoice_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='original_source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_source_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
