# Generated by Django 5.1 on 2026-03-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0007_invoice_original_source_id_and_more'),
        ('patients', '0003_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientcategory'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
