# Generated by Django 5.1 on 2026-03-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0008_receipt_category_receipt_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='completed',
        ),
    ]
