# Generated by Django 5.1 on 2026-03-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0009_remove_receipt_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_type',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
