# Generated by Django 5.1 on 2026-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0011_deposit_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='payment_to',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS'), ('Bank Deposit', 'Bank Deposit'), ('Others', 'Others')], default='Cash', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS'), ('Bank Deposit', 'Bank Deposit'), ('Others', 'Others')], default='Cash', max_length=12, null=True),
        ),
    ]
