# Generated by Django 5.1 on 2026-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0012_refund_payment_to_alter_deposit_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS'), ('Bank Deposit', 'Bank Deposit'), ('Others', 'Others')], default='Cash', max_length=50, null=True),
        ),
    ]
