# Generated by Django 5.1 on 2026-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0013_alter_deposit_amount_alter_deposit_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
