# Generated by Django 5.1 on 2026-04-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0014_alter_receipt_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionupdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionupdate',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
