# Generated by Django 5.1 on 2026-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0015_transactionupdate_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionupdate',
            name='total_available_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionupdate',
            name='total_invoiced_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
