# Generated by Django 5.1 on 2026-06-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0016_transactionupdate_total_available_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='invoice_id',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
