# Generated by Django 5.1 on 2026-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0017_refund_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
