# Generated by Django 5.1 on 2026-08-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billings', '0018_deposit_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_option',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
