# Generated by Django 5.1 on 2026-03-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPD_pharm', '0002_opdadministereddrugs_anc_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdadministereddrugs',
            name='completed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
