# Generated by Django 5.1 on 2026-08-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPD_pharm', '0007_remove_opdadministereddrugs_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='opddrugs',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
