# Generated by Django 5.1 on 2026-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPD_pharm', '0008_opddrugs_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdadministereddrugs',
            name='UoM',
            field=models.CharField(blank=True, choices=[('', '--Select Units--'), ('ampoules', 'Ampoules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('cartons', 'Cartons'), ('rolls', 'Rolls'), ('packs', 'Packs'), ('pieces', 'Pieces'), ('prefilled_syringe', 'Prefilled Syringe'), ('sachets', 'Sachets'), ('syringes', 'Syringes'), ('tins', 'Tins'), ('tubes', 'Tubes'), ('vial', 'Vial'), ('others', 'Others'), ('each', 'Each'), ('mls', 'mls (mililiters)'), ('mg', 'mg'), ('mcg', 'mcg'), ('g', 'grams'), ('IU', 'IU'), ('capsules', 'Capsules'), ('tablets', 'Tablets'), ('suppository', 'Suppository'), ('pessary', 'Pessary'), ('drops', 'Drops'), ('immuno', 'Immuno'), ('puffs', 'Puffs (Inhaler)')], default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='opddrugs',
            name='minimum_UoM',
            field=models.CharField(blank=True, choices=[('', '--Select Units--'), ('ampoules', 'Ampoules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('cartons', 'Cartons'), ('rolls', 'Rolls'), ('packs', 'Packs'), ('pieces', 'Pieces'), ('prefilled_syringe', 'Prefilled Syringe'), ('sachets', 'Sachets'), ('syringes', 'Syringes'), ('tins', 'Tins'), ('tubes', 'Tubes'), ('vial', 'Vial'), ('others', 'Others'), ('each', 'Each'), ('mls', 'mls (mililiters)'), ('mg', 'mg'), ('mcg', 'mcg'), ('g', 'grams'), ('IU', 'IU'), ('capsules', 'Capsules'), ('tablets', 'Tablets'), ('suppository', 'Suppository'), ('pessary', 'Pessary'), ('drops', 'Drops'), ('immuno', 'Immuno'), ('puffs', 'Puffs (Inhaler)')], default='', max_length=18, null=True),
        ),
    ]
