# Generated by Django 5.1 on 2026-02-21 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ANCRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_menstrual_period', models.DateField(blank=True, null=True)),
                ('gestational_age_weeks', models.IntegerField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('number_of_foetus', models.IntegerField(default=1)),
                ('bleeding', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('oedema', models.BooleanField(default=False)),
                ('placenta_previa', models.BooleanField(default=False)),
                ('blurred_vision', models.BooleanField(default=False)),
                ('breathlessness', models.BooleanField(default=False)),
                ('discharge', models.BooleanField(default=False)),
                ('current_stage', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_registrations', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='CurrentPregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stillbirth_or_neonatal_loss', models.BooleanField(blank=True, null=True)),
                ('last_baby_weight_lt_2500g', models.BooleanField(blank=True, null=True)),
                ('previous_hospital_admission_htn', models.BooleanField(blank=True, null=True)),
                ('multiple_pregnancy', models.BooleanField(blank=True, null=True)),
                ('age_less_than_16', models.BooleanField(blank=True, null=True)),
                ('isoimmunization_rh', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('not_applicable', 'N/A')], default='not_applicable', max_length=20)),
                ('pelvic_mass', models.BooleanField(blank=True, null=True)),
                ('insulin_dependent_diabetes', models.BooleanField(blank=True, null=True)),
                ('substance_abuse', models.BooleanField(blank=True, null=True)),
                ('anc_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_pregnancy', to='ANC.ancregistration')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severe_anaemia', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('cardiac_disease', models.BooleanField(default=False)),
                ('breast_cancer', models.BooleanField(default=False)),
                ('gall_bladder_disease', models.BooleanField(default=False)),
                ('renal_disease', models.BooleanField(default=False)),
                ('peptic_ulcer_disease', models.BooleanField(default=False)),
                ('sickle_cell_disease', models.BooleanField(default=False)),
                ('diabetes_mellitus', models.BooleanField(default=False)),
                ('chronic_cough_tuberculosis', models.BooleanField(default=False)),
                ('liver_disease_jaundice', models.BooleanField(default=False)),
                ('thyroid_disease', models.BooleanField(default=False)),
                ('epilepsy', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('other_conditions', models.TextField(blank=True, null=True)),
                ('family_history_hypertension', models.BooleanField(default=False)),
                ('family_history_breast_cancer', models.BooleanField(default=False)),
                ('family_history_ovarian_tumor', models.BooleanField(default=False)),
                ('family_history_cervical_cancer', models.BooleanField(default=False)),
                ('family_history_diabetes', models.BooleanField(default=False)),
                ('family_history_chromosomal_abnormalities', models.BooleanField(default=False)),
                ('family_history_recurrent_discharge', models.BooleanField(default=False)),
                ('family_history_other', models.TextField(blank=True, null=True)),
                ('anc_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_medical', to='ANC.ancregistration')),
            ],
        ),
        migrations.CreateModel(
            name='LabTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdrl_result', models.CharField(blank=True, max_length=50, null=True)),
                ('vdrl_awaiting', models.BooleanField(default=True)),
                ('genotype_result', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC'), ('SC', 'SC')], max_length=10, null=True)),
                ('genotype_awaiting', models.BooleanField(default=True)),
                ('rhesus_factor', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20, null=True)),
                ('rhesus_awaiting', models.BooleanField(default=True)),
                ('urine_glucose', models.CharField(blank=True, max_length=50, null=True)),
                ('urine_glucose_awaiting', models.BooleanField(default=True)),
                ('hiv_result', models.CharField(blank=True, max_length=50, null=True)),
                ('hiv_awaiting', models.BooleanField(default=True)),
                ('hepatitis_b', models.CharField(blank=True, max_length=50, null=True)),
                ('hepatitis_b_awaiting', models.BooleanField(default=True)),
                ('hepatitis_c', models.CharField(blank=True, max_length=50, null=True)),
                ('hepatitis_c_awaiting', models.BooleanField(default=True)),
                ('hb_level', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('hb_awaiting', models.BooleanField(default=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5, null=True)),
                ('urine_protein', models.CharField(blank=True, max_length=50, null=True)),
                ('urine_protein_awaiting', models.BooleanField(default=True)),
                ('other_tests', models.JSONField(blank=True, default=dict)),
                ('anc_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='ANC.ancregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ObstetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pregnancy', models.BooleanField(blank=True, null=True)),
                ('three_or_more_abortions', models.BooleanField(blank=True, null=True)),
                ('last_baby_weight_gt_4500g', models.BooleanField(blank=True, null=True)),
                ('previous_caesarean_section', models.BooleanField(blank=True, null=True)),
                ('previous_surgery_reproductive_tract', models.BooleanField(blank=True, null=True)),
                ('age_more_than_40', models.BooleanField(blank=True, null=True)),
                ('vaginal_bleeding', models.BooleanField(blank=True, null=True)),
                ('diastolic_bp_90_or_more', models.BooleanField(blank=True, null=True)),
                ('family_history_twins', models.BooleanField(blank=True, null=True)),
                ('myomectomy', models.BooleanField(default=False)),
                ('removal_of_septum', models.BooleanField(default=False)),
                ('cone_biopsy', models.BooleanField(default=False)),
                ('classical_cs', models.BooleanField(default=False)),
                ('cervical_cerclage', models.BooleanField(default=False)),
                ('previous_pregnancies', models.JSONField(blank=True, default=list)),
                ('anc_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obstetric_history', to='ANC.ancregistration')),
            ],
        ),
    ]
