# Generated by Django 5.1 on 2026-02-21 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANC', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalmedical',
            old_name='family_history_other',
            new_name='family_history',
        ),
        migrations.RenameField(
            model_name='generalmedical',
            old_name='other_conditions',
            new_name='others_medical_history',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='age_less_than_16',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='anc_registration',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='insulin_dependent_diabetes',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='isoimmunization_rh',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='last_baby_weight_lt_2500g',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='multiple_pregnancy',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='pelvic_mass',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='previous_hospital_admission_htn',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='previous_stillbirth_or_neonatal_loss',
        ),
        migrations.RemoveField(
            model_name='currentpregnancy',
            name='substance_abuse',
        ),
        migrations.RemoveField(
            model_name='generalmedical',
            name='anc_registration',
        ),
        migrations.RemoveField(
            model_name='generalmedical',
            name='family_history_breast_cancer',
        ),
        migrations.RemoveField(
            model_name='generalmedical',
            name='family_history_cervical_cancer',
        ),
        migrations.RemoveField(
            model_name='generalmedical',
            name='family_history_chromosomal_abnormalities',
        ),
        migrations.RemoveField(
            model_name='generalmedical',
            name='family_history_diabetes',
        ),
        migrations.RemoveField(
            model_name='generalmedical',
            name='family_history_hypertension',
        ),
        migrations.RemoveField(
            model_name='generalmedical',
            name='family_history_ovarian_tumor',
        ),
        migrations.RemoveField(
            model_name='generalmedical',
            name='family_history_recurrent_discharge',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='anc_registration',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='genotype_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='genotype_result',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='hb_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='hb_level',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='hepatitis_b_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='hepatitis_c_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='hiv_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='hiv_result',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='other_tests',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='rhesus_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='urine_glucose_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='urine_protein_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='vdrl_awaiting',
        ),
        migrations.RemoveField(
            model_name='labtests',
            name='vdrl_result',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='age_more_than_40',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='anc_registration',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='cervical_cerclage',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='classical_cs',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='cone_biopsy',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='diastolic_bp_90_or_more',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='first_pregnancy',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='last_baby_weight_gt_4500g',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='myomectomy',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='previous_pregnancies',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='removal_of_septum',
        ),
        migrations.RemoveField(
            model_name='obstetrichistory',
            name='three_or_more_abortions',
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='bleeding',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='blurred_vision',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='breathlessness',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='discharge',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='expected_date_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='gestational_age_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='gestational_period_from_ultrasound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='history_of_present_pregnancy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='last_menstrual_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='number_of_foetus',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='oedema',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='placenta_previa',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='vomiting',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='generalmedical',
            name='known_substance_abuse',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='labtests',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC'), ('CC', 'CC'), ('Unknown', 'Unknown')], default='Unknown', max_length=8),
        ),
        migrations.AddField(
            model_name='labtests',
            name='hb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='labtests',
            name='hiv',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], default='Negative', max_length=20),
        ),
        migrations.AddField(
            model_name='labtests',
            name='pregnancy_test',
            field=models.CharField(default='Positive', max_length=20),
        ),
        migrations.AddField(
            model_name='labtests',
            name='vdrl',
            field=models.CharField(default='Awaiting Result', max_length=20),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='age_gt_40_years',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='age_lt_16_years',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='birthweight_gt_4500g',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='birthweight_lt_2500g',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='diastolic_bp_gt_90',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='history_spontaneous_abortions',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='insulin_dependent_diabetes',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='is_first_pregnancy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='isoimmunization_rh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='last_pregnancy_hospital_admission',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='multiple_pregnancy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='pelvic_mass',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='previous_stillbirth_neonatal_loss',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='asthma',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='breast_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='cardiac_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='chronic_cough_tuberculosis',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='diabetes_mellitus',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='epilepsy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='gall_bladder_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='hypertension',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='liver_disease_jaundice',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='peptic_ulcer_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='renal_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='severe_anaemia',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='sickle_cell_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalmedical',
            name='thyroid_disease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=8),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='hepatitis_b',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='hepatitis_c',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='rhesus_factor',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], default='Negative', max_length=10),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='urine_glucose',
            field=models.CharField(default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='urine_protein',
            field=models.CharField(default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='obstetrichistory',
            name='family_history_twins',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='obstetrichistory',
            name='previous_caesarean_section',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='obstetrichistory',
            name='previous_surgery_reproductive_tract',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obstetrichistory',
            name='vaginal_bleeding',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
        migrations.CreateModel(
            name='AntenatalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenatal_visits', to='patients.patientprofile')),
            ],
        ),
        migrations.AddField(
            model_name='currentpregnancy',
            name='visit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_pregnancy', to='ANC.antenatalvisit'),
        ),
        migrations.AddField(
            model_name='generalmedical',
            name='visit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_medical', to='ANC.antenatalvisit'),
        ),
        migrations.AddField(
            model_name='labtests',
            name='visit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='ANC.antenatalvisit'),
        ),
        migrations.AddField(
            model_name='obstetrichistory',
            name='visit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obstetric_history', to='ANC.antenatalvisit'),
        ),
    ]
