# Generated by Django 5.1 on 2026-02-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANC', '0002_rename_family_history_other_generalmedical_family_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtests',
            name='hepatitis_b',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown'), ('Awaiting Result', 'Awaiting Result')], default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='hepatitis_c',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown'), ('Awaiting Result', 'Awaiting Result')], default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='hiv',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown'), ('Awaiting Result', 'Awaiting Result')], default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='rhesus_factor',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown'), ('Awaiting Result', 'Awaiting Result')], default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='obstetrichistory',
            name='previous_surgery_reproductive_tract',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Myomectomy', 'Myomectomy'), ('Removal of Septum', 'Removal of Septum'), ('Cone Biopsy', 'Cone Biopsy'), ('Classical CS', 'Classical CS'), ('Cervical Cerclage', 'Cervical Cerclage'), ('Others', 'Others')], default='N/A', max_length=20, null=True),
        ),
    ]
