# Generated by Django 5.1 on 2026-02-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANC', '0003_alter_labtests_hepatitis_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtests',
            name='vdrl',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown'), ('Awaiting Result', 'Awaiting Result')], default='Awaiting Result', max_length=20),
        ),
    ]
