# Generated by Django 5.1 on 2026-02-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ANC', '0006_remove_antenatalvisit_staff_currentpregnancy_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ancdetails',
            name='fgm_counseled',
        ),
        migrations.RemoveField(
            model_name='ancdetails',
            name='malaria_ipt4_plus',
        ),
    ]
