# Generated by Django 5.1 on 2026-03-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANC', '0009_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='foetal_movement',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=3),
        ),
    ]
