# Generated by Django 5.1 on 2026-03-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANC', '0010_examination_foetal_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='PVC',
            new_name='pvc',
        ),
        migrations.AlterField(
            model_name='examination',
            name='bp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='pulse_rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
