# Generated by Django 5.1 on 2026-03-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANC', '0011_rename_pvc_examination_pvc_alter_examination_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='relationship_of_pp_to_brim',
            field=models.CharField(choices=[('0/5', '0/5'), ('1/5', '1/5'), ('2/5', '2/5'), ('3/5', '3/5'), ('4/5', '4/5'), ('5/5', '5/5'), ('N/A', 'N/A')], default='N/A', max_length=3),
        ),
    ]
