# Generated by Django 5.1 on 2026-04-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANC', '0012_alter_examination_relationship_of_pp_to_brim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='condition_of_vagina',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Spotting', 'Spotting'), ('Discharge', 'Discharge'), ('Bleeding', 'Bleeding'), ('Warts', 'Warts')], default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='foetal_heart',
            field=models.CharField(choices=[('Foetal heart heard(FHH)', 'Foetal heart heard(FHH)'), ('Mutiple foetal heart heard (MFHH)', 'Mutiple foetal heart heard (MFHH)'), ('mutiple foetal heart not heard (MFHNH)', 'mutiple foetal heart not heard (MFHNH)')], default='Foetal heart heard(FHH)', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='foetal_heart_rate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='foetal_movement',
            field=models.CharField(choices=[('Foetal movement felt (FMF)', 'Foetal movement felt (FMF)'), ('Foetal movement not felt (FMNF)', 'Foetal movement not felt (FMNF)'), ('Multiple foetal movement felt (MFMF)', 'Multiple foetal movement felt (MFMF)')], default='Foetal movement felt (FMF)', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='foetal_presentation',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Cephalic', 'Cephalic'), ('Breech', 'Breech'), ('Transperse', 'Transperse'), ('Oblique', 'Oblique')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='oedema',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='position',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Right Occiput Anterior', 'Right Occiput Anterior'), ('Right Occiput Transperse', 'Right Occiput Transperse'), ('Right Occiput Posterior', 'Right Occiput Posterior'), ('Left Occiput Anterior', 'Left Occiput Anterior'), ('Left Occiput Transperse', 'Left Occiput Transperse'), ('Left Occiput Posterior', 'Left Occiput Posterior')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='relationship_of_pp_to_brim',
            field=models.CharField(choices=[('0/5', '0/5'), ('1/5', '1/5'), ('2/5', '2/5'), ('3/5', '3/5'), ('4/5', '4/5'), ('5/5', '5/5'), ('N/A', 'N/A')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='urine_protein',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Trace', 'Trace'), ('Positive +', 'Positive +'), ('Positive ++', 'Positive ++'), ('Positive +++', 'Positive +++')], default='Negative', max_length=60),
        ),
        migrations.AlterField(
            model_name='examination',
            name='urine_sugar',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Trace', 'Trace'), ('Positive +', 'Positive +'), ('Positive ++', 'Positive ++'), ('Positive +++', 'Positive +++')], default='Negative', max_length=60),
        ),
    ]
