# Generated by Django 5.1 on 2026-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm', '0003_ipdadministereddrugs_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdadministereddrugs',
            name='total',
        ),
        migrations.AddField(
            model_name='ipdadministereddrugs',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
