# Generated by Django 5.1 on 2026-05-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm', '0006_ipdadministereddrugs_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdadministereddrugs',
            name='strength',
        ),
    ]
