# Generated by Django 5.1 on 2026-08-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm', '0007_remove_ipdadministereddrugs_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
