# Generated by Django 4.2.29 on 2026-07-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.RemoveField(
            model_name='scheduledreport',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ScheduledReport',
        ),
    ]
