# Generated by Django 5.1 on 2026-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologylab',
            name='anc_weeks',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
