# Generated by Django 5.1 on 2026-03-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_lab', '0002_radiologylab_anc_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologylab',
            name='completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
