# Generated by Django 5.1 on 2026-06-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_lab', '0003_radiologylab_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologylab',
            name='exception_bill',
            field=models.BooleanField(default=False),
        ),
    ]
