# Generated by Django 5.1 on 2026-08-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patientprofile_deactivated_date'),
        ('radio_lab', '0004_radiologylab_exception_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiolabinventory',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tariffs', to='patients.patientplan'),
        ),
        migrations.AlterField(
            model_name='radiolabinventory',
            name='type',
            field=models.CharField(choices=[('L', 'Lab'), ('R', 'Scan')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='radiolabinventory',
            unique_together={('item_id', 'plan')},
        ),
    ]
