# Generated by Django 5.1 on 2026-02-13 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdministerDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('UoM', models.CharField(blank=True, choices=[('', '--Select Units--'), ('ampoules', 'Ampoules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('cartons', 'Cartons'), ('rolls', 'Rolls'), ('packs', 'Packs'), ('pieces', 'Pieces'), ('prefilled_syringe', 'Prefilled Syringe'), ('sachets', 'Sachets'), ('syringes', 'Syringes'), ('tins', 'Tins'), ('tubes', 'Tubes'), ('vial', 'Vial'), ('others', 'Others'), ('each', 'Each'), ('mls', 'mls (mililiters)')], default='', max_length=22, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientcategory')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientplan')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=20)),
                ('minimum_UoM', models.CharField(blank=True, choices=[('', '--Select Units--'), ('ampoules', 'Ampoules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('cartons', 'Cartons'), ('rolls', 'Rolls'), ('packs', 'Packs'), ('pieces', 'Pieces'), ('prefilled_syringe', 'Prefilled Syringe'), ('sachets', 'Sachets'), ('syringes', 'Syringes'), ('tins', 'Tins'), ('tubes', 'Tubes'), ('vial', 'Vial'), ('others', 'Others'), ('each', 'Each'), ('mls', 'mls (mililiters)')], default='', max_length=22, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_id', models.CharField(help_text='13 Characters max', max_length=13, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.PositiveIntegerField()),
                ('minimum_UoM', models.CharField(blank=True, choices=[('', '--Select Units--'), ('ampoules', 'Ampoules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('cartons', 'Cartons'), ('rolls', 'Rolls'), ('packs', 'Packs'), ('pieces', 'Pieces'), ('prefilled_syringe', 'Prefilled Syringe'), ('sachets', 'Sachets'), ('syringes', 'Syringes'), ('tins', 'Tins'), ('tubes', 'Tubes'), ('vial', 'Vial'), ('others', 'Others'), ('each', 'Each'), ('mls', 'mls (mililiters)')], default='', max_length=22, null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('status', models.IntegerField(default=1, null=True)),
                ('activation_status', models.IntegerField(default=1, null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode_image')),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expiry_flag_in', models.CharField(blank=True, choices=[('', '--Select Periods--'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='', max_length=10, null=True)),
                ('expiry_flag_in_num', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_names', models.CharField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('source', models.CharField(max_length=30, null=True)),
                ('destination', models.CharField(max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('minimum_UoM', models.CharField(max_length=20, null=True)),
                ('staff2', models.CharField(max_length=50, null=True)),
                ('status', models.PositiveBigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_names', models.CharField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_type', models.CharField(max_length=10, null=True)),
                ('destination', models.CharField(max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('minimum_UoM', models.CharField(max_length=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('payment', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense_id', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.expense')),
            ],
        ),
    ]
