# Generated by Django 5.1 on 2026-08-11 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_administerdrugs_uom_alter_expense_minimum_uom_and_more'),
        ('patients', '0008_alter_patientprofile_deactivated_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(choices=[('ipd_pharm1', 'IPD Pharmacy 1'), ('ipd_pharm2', 'IPD Pharmacy 2'), ('ipd_pharm3', 'IPD Pharmacy 3'), ('opd_pharm1', 'OPD Pharmacy 1'), ('opd_pharm2', 'OPD Pharmacy 2')], max_length=20)),
                ('product_id', models.CharField(db_index=True, max_length=13)),
                ('product_name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientplan')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['store_id', 'product_name'],
                'unique_together': {('store_id', 'product_id', 'plan')},
            },
        ),
    ]
