# Generated by Django 5.1 on 2026-08-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_pharmacytariff'),
        ('patients', '0008_alter_patientprofile_deactivated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacytariff',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterUniqueTogether(
            name='pharmacytariff',
            unique_together={('product_id', 'plan')},
        ),
        migrations.RemoveField(
            model_name='pharmacytariff',
            name='store_id',
        ),
    ]
