# Generated by Django 5.1 on 2026-08-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_pharmacytariff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
