# Generated by Django 5.1 on 2026-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorwaitinglist',
            name='anc_weeks',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='doctorwaitinglist',
            name='unit',
            field=models.CharField(blank=True, default='cm', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='anc_weeks',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
