# Generated by Django 5.1 on 2026-03-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0002_doctorwaitinglist_anc_weeks_doctorwaitinglist_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nursewaitinglist',
            options={},
        ),
    ]
