# Generated by Django 5.1 on 2026-03-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0003_alter_nursewaitinglist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nursewaitinglist',
            options={'ordering': ['critical_request', 'created_date']},
        ),
    ]
