# Generated by Django 5.1 on 2026-03-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0005_getregistrationfee_regfee_transactiontb'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientencounter',
            name='anc_weeks',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
