# Generated by Django 5.1 on 2026-04-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0006_patientencounter_anc_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('icd10_code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'description'],
            },
        ),
        migrations.AlterField(
            model_name='patientencounter',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='presentingcomplaint',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
