# Generated by Django 5.1 on 2026-04-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0007_patientdiagnosis_alter_patientencounter_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='icd10_code',
            field=models.CharField(max_length=10),
        ),
    ]
