# Generated by Django 5.1 on 2026-04-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0008_alter_patientdiagnosis_icd10_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorwaitinglist',
            name='completed_by',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nursewaitinglist',
            name='completed_by',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
