# Generated by Django 5.1 on 2026-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0010_alter_doctorwaitinglist_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursewaitinglist',
            name='completed_by',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
