# Generated by Django 5.1 on 2026-05-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0011_alter_nursewaitinglist_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorwaitinglist',
            name='encounter_status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
