# Generated by Django 5.1 on 2026-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0012_doctorwaitinglist_encounter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='blood_glucose',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='bmi',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='bp',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='oxygen_volume',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='pulse',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='respiratory_rate',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='sp_02',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='temperature',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='waist_circumference',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='weight',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
