# Generated by Django 5.1 on 2026-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0013_alter_doctorwaitinglist_blood_glucose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='height',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
    ]
