# Generated by Django 5.1 on 2026-05-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0014_alter_doctorwaitinglist_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='blood_glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='bp',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='oxygen_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='respiratory_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='sp_02',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='waist_circumference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorwaitinglist',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
