# Generated by Django 5.1 on 2026-05-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0016_writtenprescriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorwaitinglist',
            old_name='waist_circumference',
            new_name='urine_glucose',
        ),
        migrations.RemoveField(
            model_name='doctorwaitinglist',
            name='bowel_movement',
        ),
        migrations.RemoveField(
            model_name='doctorwaitinglist',
            name='pain_score',
        ),
        migrations.AddField(
            model_name='doctorwaitinglist',
            name='urine_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorwaitinglist',
            name='urine_protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
