# Generated by Django 5.1 on 2026-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0017_rename_waist_circumference_doctorwaitinglist_urine_glucose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherservice',
            name='exception_bill',
            field=models.BooleanField(default=False),
        ),
    ]
