# Generated by Django 5.1 on 2026-06-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0018_otherservice_exception_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursewaitinglist',
            name='exception_bill',
            field=models.BooleanField(default=False),
        ),
    ]
