# Generated by Django 5.1 on 2026-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_operations', '0020_antenatalfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regfee',
            name='creator',
        ),
        migrations.AddField(
            model_name='regfee',
            name='plan_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
