# Generated by Django 5.1 on 2026-05-03 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change'), ('pin_reset', 'PIN Reset'), ('pin_created', 'PIN Created'), ('pin_change', 'PIN Changed'), ('deactivated', 'Account Deactivated'), ('activated', 'Account Activated'), ('profile_update', 'Profile Update'), ('profile_picture_update', 'Profile Picture Update'), ('failed_login', 'Failed Login Attempt'), ('session_expired', 'Session Expired'), ('account_accessed', 'Account Accessed by Admin')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('device_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('referrer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('page_accessed', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='myAdmins_us_user_id_8cbf26_idx'), models.Index(fields=['activity_type'], name='myAdmins_us_activit_da395e_idx'), models.Index(fields=['ip_address'], name='myAdmins_us_ip_addr_7dc8ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='myAdmins_us_user_id_78c6cb_idx'), models.Index(fields=['last_activity'], name='myAdmins_us_last_ac_df26de_idx'), models.Index(fields=['session_key'], name='myAdmins_us_session_c8356d_idx')],
                'unique_together': {('user', 'session_key')},
            },
        ),
    ]
