# Generated by Django 5.1 on 2026-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmins', '0003_packages_packagesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesdata',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagesdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
