# Generated by Django 5.1 on 2026-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmins', '0004_packagesdata_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
