# Generated by Django 5.1 on 2026-08-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm3', '0007_remove_ipd3administereddrugs_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd3drugs',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
