# Generated by Django 5.1 on 2026-02-13 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='patients.patientcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=100)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('', '--Select Gender--'), ('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='', max_length=18)),
                ('patient_type', models.CharField(blank=True, choices=[('', '--Select Marital Status--'), ('Married', 'Married'), ('Single', 'Single'), ('Others', 'Others')], default='', max_length=18)),
                ('phone_number', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField(null=True)),
                ('email_address', models.EmailField(max_length=254, null=True, unique=True)),
                ('hospital_number', models.CharField(db_index=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('relationship_to_patient', models.CharField(max_length=100, null=True)),
                ('phone_numbers', models.CharField(max_length=100, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(default='patient-profile/avatar.svg', null=True, upload_to='patient-profile/')),
                ('allergies', models.TextField(blank=True, null=True)),
                ('active', models.PositiveIntegerField(db_index=True, default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patientcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patientplan')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinician', models.CharField(max_length=40, null=True)),
                ('purpose', models.CharField(max_length=58, null=True)),
                ('visit_type', models.CharField(choices=[('', '--Select Visit Type--'), ('New-case', 'New Case'), ('Follow-up', 'Follow-up'), ('Review', 'Review'), ('First visit after discharge', 'First visit after discharge'), ('Drug-refill', 'Drug refill')], default='', max_length=38)),
                ('arrival_date', models.DateField(null=True)),
                ('arrival_time', models.TimeField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patientprofile')),
            ],
        ),
    ]
