# Generated by Django 5.1 on 2026-03-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='anc_weeks',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
