# Generated by Django 5.1 on 2026-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientappointment_anc_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('', '--Select Gender--'), ('Female', 'Female'), ('Male', 'Male')], default='', max_length=18),
        ),
    ]
