# Generated by Django 5.1 on 2026-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
