# Generated by Django 5.1 on 2026-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientprofile_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
