# Generated by Django 5.1 on 2026-07-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientprofile_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='deactivated_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='deactivated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
