# Generated by Django 5.1 on 2026-08-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientprofile_deactivated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='deactivated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
