# Generated by Django 5.1 on 2026-08-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patientprofile_deactivated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='deactivated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
