# Generated by Django 5.1 on 2026-09-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patientprofile_deactivated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='packages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
