# Generated by Django 5.1 on 2026-10-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientprofile_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='packages',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
