# Generated by Django 5.1 on 2026-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd2administereddrugs',
            name='anc_weeks',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
