# Generated by Django 5.1 on 2026-03-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm2', '0002_ipd2administereddrugs_anc_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd2administereddrugs',
            name='completed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
