# Generated by Django 5.1 on 2026-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm2', '0005_alter_ipd2administereddrugs_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd2administereddrugs',
            name='strength',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
