# Generated by Django 5.1 on 2026-05-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm2', '0006_ipd2administereddrugs_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipd2administereddrugs',
            name='strength',
        ),
    ]
