# Generated by Django 5.1 on 2026-08-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPD_pharm2', '0007_remove_ipd2administereddrugs_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd2drugs',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
